---
format: html
title: "Workshop Materials"
---

To get access to the workshop materials, please clone the repo:

<https://github.com/mattfarrow1/text-mining-workshop.git>

```{r}
#| label: setup
#| include: false
library(dplyr)
library(purrr)
library(fs)
library(gt)
work_files <- fs::dir_info("materials/workshop/", type = "file", recurse = TRUE) |> 
  mutate(file = fs::path_file(path),
         folder = stringr::str_remove(fs::path_dir(path), "materials/workshop/")) |>
  select(folder, file) |> 
  group_split(folder)
```

```{r}
#| echo: false
#| results: asis
for (i in 1:length(work_files)) {
  folder_path <- gsub(
    x = work_files[[i]]$folder,
    pattern = "materials/workshop/",
    replacement = "") |> unique()
  print(gt(work_files[[i]]) |> 
          tab_header(title = folder_path) |> 
          cols_hide(columns = c(1)) |> 
          cols_label(file = "Filename") |> 
          opt_stylize(style = 3, color = "blue", add_row_striping = TRUE) |> 
          opt_table_font(stack = "rounded-sans")
        )
}

```

